- server: localhost
  os:
    vendor: ubuntu
    version: 14.04
  connection:
    ip: 127.0.0.1
    port: 22 
    username: root
    password: 32768
  installed:
    - nginx
    - php5-common 
    - php5-cli 
    - php5-fpm
  uninstalled:
    - apache2 
  files:
    /usr/share/nginx/html/index.php: 
      source: files/index.php
      on_change:
        restart: nginx
      owner: www-data
      group: www-data
      perms: 755
    /etc/nginx/sites-available/default:
      source: files/default
      owner: root
      group: root
      perms: 644
    /etc/nginx/sites-enabled/default:
      symlink: /etc/nginx/sites-enabled/default
- server: ssh.ccoffey.ie
  connection:
    ip: 127.0.0.1
    port: 2202
    username: root
    password: 32768
  os:
    vendor: arch
    version: rolling
