---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 5080, auto_correct: true}]
  - ["forwarded_port", {guest: 443, host: 5443, auto_correct: true}]

provisioner:
  name: shell

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
    attributes:

verifier:
  ruby_bindir: '/usr/bin'
